### ISSUE TITLE
可以做成 web app 吗？

### ISSUE THREAD

**Issue by physixfan** [wandergis/putian-hospitals#7]

**Comment by wandergis** [comment]
暂时只简单适配了下移动端，有兴趣有能力的童鞋可参考代码借助cordova封装成webapp

**Comment by zhuyunji** [comment]
请问高德地图的tilelayer是怎么调用的，只用这个地址//webrd0{s}.is.autonavi.com/appmaptile?lang=zh_cn&size=1&scale=1&style=8&x={x}&y={y}&z={z} 就可以了吗？谢谢！

**Comment by wandergis** [comment]
@zhuyunji 这是标准瓦片的组织方式，按照缩放等级z和 行列号 x y 去确定单张瓦片，经过leaflet api加载到对应位置。 可以参考 [webgis学习目录](http://www.thinkgis.cn/topic/541ac2e15eb69f9abd038dfc)  还有 [瓦片原理及换算](http://cntchen.github.io/2016/05/09/%E5%9B%BD%E5%86%85%E4%B8%BB%E8%A6%81%E5%9C%B0%E5%9B%BE%E7%93%A6%E7%89%87%E5%9D%90%E6%A0%87%E7%B3%BB%E5%AE%9A%E4%B9%89%E5%8F%8A%E8%AE%A1%E7%AE%97%E5%8E%9F%E7%90%86/)
