### ISSUE TITLE
用https访问提示：Your connection is not private

### ISSUE THREAD

**Issue by hairuo** [wandergis/putian-hospitals#8]
#### 问题描述：

最近发现使用chrome访问https://wandergis.com/hospital-viz/index.htm  提示：
Your connection is not private

Attackers might be trying to steal your information from wandergis.com (for example, passwords, messages, or credit cards). NET::ERR_CERT_COMMON_NAME_INVALID

换成firefox访问提示：
Your connection is not secure

The owner of wandergis.com has configured their website improperly. To protect your information from being stolen, Firefox has not connected to this website.
#### 尝试办法:

1.将https改成http之后访问正常。
2.不改变https，而是通过XX-net等代理访问也可以正常打开。

考虑到如果大多数用户并不使用翻墙代理，可能会遇到https开头网址被推荐访问失败，从而无法即时获取有效信息，因此反馈一下。

谢谢！

**Comment by wandergis** [comment]
嗯 感谢提醒 之前绑定了免费的ssl证书，但是那个服务停止了 当时使用https是因为这样可以获取手机位置，我改成http的吧 thks
